// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrintMe.Server.Persistence;

#nullable disable

namespace PrintMe.Server.Migrations
{
    [DbContext(typeof(PrintMeDbContext))]
    [Migration("20250202183942_AddEmailVerificationPropertiesToUser")]
    partial class AddEmailVerificationPropertiesToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrintMe.Server.Persistence.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone_number");

                    b.Property<int?>("UserStatusId")
                        .HasColumnType("integer")
                        .HasColumnName("user_status_id");

                    b.Property<bool?>("ShouldHidePhoneNumber")
                        .HasColumnType("boolean")
                        .HasColumnName("should_hide_phone_number")
                        .HasDefaultValue(true);

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salt");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("user_role_id");

                    b.Property<string>("ConfirmationToken")
                        .HasColumnType("text")
                        .HasColumnName("confirmation_token");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.HasKey("UserId")
                        .HasName("user_pkey");

                    b.HasIndex("Email")
                        .HasDatabaseName("idx_user_email");

                    b.HasIndex("PhoneNumber")
                        .HasDatabaseName("idx_user_phone_number");

                    b.HasIndex("UserRoleId")
                        .HasDatabaseName("idx_user_role_id");

                    b.HasIndex("UserStatusId")
                        .HasDatabaseName("idx_user_status_id");

                    b.ToTable("user");
                });
#pragma warning restore 612, 618
        }
    }
}